# Generated by Django 5.1.1 on 2024-10-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("water_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="goal",
            field=models.FloatField(default=4.0),
        ),
        migrations.AlterField(
            model_name="waterintake",
            name="intake",
            field=models.FloatField(default=0.0),
        ),
    ]
