# Generated by Django 5.1.1 on 2024-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("water_tracker", "0002_alter_waterintake_goal_alter_waterintake_intake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="goal",
            field=models.IntegerField(default=4),
        ),
    ]
