# Generated by Django 5.1.1 on 2024-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("water_tracker", "0003_alter_waterintake_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="goal",
            field=models.FloatField(default=4.0),
        ),
    ]
