# Generated by Django 5.1.1 on 2024-10-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("water_tracker", "0004_alter_waterintake_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterintake",
            name="goal",
            field=models.FloatField(default=2.0),
        ),
    ]
