# Generated by Django 5.1.1 on 2024-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("water_intake", models.FloatField(default=0)),
                ("calorie_intake", models.FloatField(default=0)),
                ("water_goal", models.FloatField(default=2.0)),
                ("calorie_goal", models.IntegerField(default=2000)),
            ],
        ),
    ]
