# Generated by Django 5.1.1 on 2024-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_cal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caloriesintake",
            name="protein_goal",
            field=models.FloatField(default=120.0),
        ),
        migrations.AlterField(
            model_name="caloriesintake",
            name="protein",
            field=models.FloatField(default=0.0),
        ),
    ]
