# Generated by Django 5.1.1 on 2024-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_cal", "0002_caloriesintake_protein_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caloriesintake",
            name="carbs_goal",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="caloriesintake",
            name="fats_goal",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="caloriesintake",
            name="fibers_goal",
            field=models.FloatField(default=0.0),
        ),
    ]
