# Generated by Django 5.1.1 on 2024-10-14 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_cal", "0004_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Lightly Active"),
                            ("moderate", "Moderately Active"),
                            ("active", "Very Active"),
                            ("extra", "Extra Active"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calories", models.FloatField()),
                ("proteins", models.FloatField()),
                ("carbs", models.FloatField()),
                ("fats", models.FloatField()),
                ("fibers", models.FloatField()),
                ("water", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
