# Generated by Django 5.1.1 on 2024-11-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_cal", "0007_caloriesintake_calories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caloriesintake",
            name="calories",
            field=models.FloatField(default=0.0),
        ),
    ]
